version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    restart: unless-stopped
    image: zeiot/rpi-prometheus:2.2.1.arm
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier

  node-exporter:
    restart: unless-stopped
    container_name: node-exporter
    image: zeiot/rpi-node_exporter:v0.16.0-arm
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command:
#      - '--collector.procfs=/host/proc'
#      - '--collector.sysfs=/host/sysfs'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - 9100:9100
    networks:
      - back-tier

  grafana:
    restart: unless-stopped
    image: fg2it/grafana-armhf:v5.0.4
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
    environment:
      - GF_INSTALL_PLUGINS=natel-discrete-panel